const DEFAULT_CAROUSEL_SLIDES = [
  {
    imageUrl: '/img/Img_Donations_1.jpeg',
    caption: 'Doacao - Imagem 1',
    altText: 'Doacao - Imagem 1',
    order: 1,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_2.jpeg',
    caption: 'Doacao - Imagem 2',
    altText: 'Doacao - Imagem 2',
    order: 2,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_3.jpeg',
    caption: 'Doacao - Imagem 3',
    altText: 'Doacao - Imagem 3',
    order: 3,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_4.jpeg',
    caption: 'Doacao - Imagem 4',
    altText: 'Doacao - Imagem 4',
    order: 4,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_5.jpeg',
    caption: 'Doacao - Imagem 5',
    altText: 'Doacao - Imagem 5',
    order: 5,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_6.jpeg',
    caption: 'Doacao - Imagem 6',
    altText: 'Doacao - Imagem 6',
    order: 6,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_7.jpeg',
    caption: 'Doacao - Imagem 7',
    altText: 'Doacao - Imagem 7',
    order: 7,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_8.jpeg',
    caption: 'Doacao - Imagem 8',
    altText: 'Doacao - Imagem 8',
    order: 8,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_9.jpeg',
    caption: 'Doacao - Imagem 9',
    altText: 'Doacao - Imagem 9',
    order: 9,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_10.jpeg',
    caption: 'Doacao - Imagem 10',
    altText: 'Doacao - Imagem 10',
    order: 10,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_11.jpeg',
    caption: 'Doacao - Imagem 11',
    altText: 'Doacao - Imagem 11',
    order: 11,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_12.jpeg',
    caption: 'Doacao - Imagem 12',
    altText: 'Doacao - Imagem 12',
    order: 12,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_13.jpeg',
    caption: 'Doacao - Imagem 13',
    altText: 'Doacao - Imagem 13',
    order: 13,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_14.jpeg',
    caption: 'Doacao - Imagem 14',
    altText: 'Doacao - Imagem 14',
    order: 14,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_15.jpeg',
    caption: 'Doacao - Imagem 15',
    altText: 'Doacao - Imagem 15',
    order: 15,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_16.jpeg',
    caption: 'Doacao - Imagem 16',
    altText: 'Doacao - Imagem 16',
    order: 16,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_17.jpeg',
    caption: 'Doacao - Imagem 17',
    altText: 'Doacao - Imagem 17',
    order: 17,
    visible: true,
  },
  {
    imageUrl: '/img/Img_Donations_18.jpeg',
    caption: 'Doacao - Imagem 18',
    altText: 'Doacao - Imagem 18',
    order: 18,
    visible: true,
  },
];

module.exports = {
  DEFAULT_CAROUSEL_SLIDES,
};
